# Generated by Django 2.2.3 on 2019-12-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelPartOne',
            new_name='MyModel',
        ),
    ]
