# Generated by Django 3.0 on 2019-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191215_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='encrypted_val',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
