# Generated by Django 3.0 on 2019-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mymodel_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_file',
            field=models.FileField(upload_to=''),
        ),
    ]
